USE  PROYECTO_INDIGENAS

----------------- TABLAS REPORTE -----------------
CREATE TABLE [reporte].[FACTOR](
    [ID] INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NOMBRE_COLUMNA] [varchar](50) NOT NULL,
    [ALIAS] [varchar](50) NOT NULL
)

CREATE TABLE [reporte].[REPORTE](
    [ID] INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NOMBRE] [varchar](50) NOT NULL,
    [DESCRIPCION] [varchar](50) NOT NULL,
    [FECHA_CREACION] [datetime] NOT NULL
)

CREATE TABLE [reporte].[REPORTE_FACTOR](
    [ID]  INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [ID_FACTOR] int not null FOREIGN KEY REFERENCES REPORTE.FACTOR(ID),
	[ID_REPORTE] int not null FOREIGN KEY REFERENCES REPORTE.REPORTE(ID),
	[COEFICIENTE] DECIMAL(6,3),
    [FECHA_CREACION] [datetime] NOT NULL
)

CREATE TABLE [reporte].[FILTRO](
    [ID] INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NOMBRE] [varchar](50) NOT NULL,
    [DESCRIPCION] [varchar](50) NOT NULL,
    [FECHA_CREACION] [datetime] NOT NULL
)

CREATE TABLE [reporte].[FILTRO_OPCION](
    [ID] INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	[ID_FILTRO] int not null FOREIGN KEY REFERENCES REPORTE.FILTRO(ID),
    [NOMBRE] [varchar](50) NOT NULL,
	[STATEMENT] [varchar](50) NOT NULL,
    [DESCRIPCION] [varchar](50) NOT NULL,
    [FECHA_CREACION] [datetime] NOT NULL
)

-------------- TABLAS USUARIO ---------------

CREATE TABLE [TIPO_ROL] (
  [ID_ROL] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [NOMBRE] VARCHAR(125),
  [DESCRIPCION] VARCHAR(255)
);


CREATE TABLE [TIPO_DOCUMENTO] (
  [ID_TIPO_DOCUMENTO] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [NOMBRE] VARCHAR(125)
);

CREATE TABLE [USER] (
  [ID_USUARIO] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [DOCUMENTO] VARCHAR(125),
  [NOMBRES] VARCHAR(125),
  [APELLIDOS] VARCHAR(125),
  [TELEFONO] INT,
  [EMAIL] VARCHAR(125),
  [PASSWORD] VARCHAR(125),
  [FK_ID_ROL] INT,
  [FK_ID_TIPO_DOCUMENTO] INT,
  CONSTRAINT [FK_USUARIO_ROL]
  FOREIGN KEY([FK_ID_ROL])
  REFERENCES [DBO].[TIPO_ROL] ([ID_ROL]),
   CONSTRAINT [FK_USUARIO_TIPO_DOCUMENTO]
  FOREIGN KEY([FK_ID_TIPO_DOCUMENTO])
  REFERENCES [DBO].[TIPO_DOCUMENTO] ([ID_TIPO_DOCUMENTO])

);

CREATE TABLE [FACTOR] (
  [ID_FACTOR] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [NOMBRE] VARCHAR(125),
  [DESCRIPCION] VARCHAR(125),
  [FK_ID_USUARIO] INT NULL,
  [FECHA_CREACION] DATETIME,
   CONSTRAINT [FK_FACTOR_USUARIO]
  FOREIGN KEY([FK_ID_USUARIO])
  REFERENCES [DBO].[USER] ([ID_USUARIO])
);

CREATE TABLE [TIPO_GENERO] (
  [ID_TIPO_GENERO] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [NOMBRE] VARCHAR(125),
  [DESCRIPCION] VARCHAR(255),
  [ESTADO] BIT
);




